#+title: Czas i asynchroniczność
#+author: Dawid NPM8 Małysa

** Asynchroniczność
    - =Synchroniczność= - oznacza, że operacje wykonywane są w pewnej kolejności i blokuja się na wzajem.
    - =Asynchroniczność= - oznacza że kod jest wykonywany w tle, bez blokowania innych operacji.
   To pozwala na lepsze wykorzystanie zasobów systemu i umożliwia lepsze wykonywanie wielu zadań jednocześnie.
** Wykonywanie w czasie
*** setTimeout
      #+BEGIN_SRC javascript
        setTimeout(function() {
          console.log("Hello");
        }, 1000);
      #+END_SRC
 
      #+results:
 
      =setTimeout= - wywołuje funkcję po upływie określonego czasu.
      pierwszy argument - funkcja, która ma być wywołana
      drugi argument - czas w milisekundach
      reszta argumentów - argumenty przekazywane do funkcji wykonywanej
*** setInterval
      #+BEGIN_SRC javascript
        setInterval(function() {
          console.log("Hello");
        }, 1000);
      #+END_SRC

      #+results:

      =setInterval= - wywołuje funkcję co określony czas.
      pierwszy argument - funkcja, która ma być wywołana
      drugi argument - czas w milisekundach
      reszta argumentów - argumenty przekazywane do funkcji wykonywanej
*** clearTimeout
      #+BEGIN_SRC javascript
        const id = setTimeout(function(what, name) {
          console.log(what, name);
        }, 1000, "Hello", "World");

        clearTimeout(id);
        console.log("Cleared");
      #+END_SRC

      #+results:

      =clearTimeout= - anuluje wywołanie funkcji po upływie czasu.
      pierwszy argument - id funkcji, która ma być anulowana

** Daty
*** Tworzenie Daty
        #+begin_src javascript
          const date1 = new Date(0);

          const date2 = new Date(123);

          const date3 = new Date(2019, 0, 1, 0, 0, 0, 0);

          const date4 = new Date("2019-01-01T00:00:00.000Z");
          
          const date5 = new Date("2019-01-01T00:00:00.000+02:00");
          
          console.log(date1, date2, date3, date4, date5);
        #+end_src

        #+results:

        ==Date== - obiekt reprezentujący datę i czas.
